dist: focal
language: minimal

stages:
  - test
  - name: release
    if: tag IS present AND repo = francma/wob

jobs:
  include:
    - name: Test Alpine
      stage: test
      services:
        - docker
      script:
        - |
          printf 'set -eu
          apk update && apk add meson wayland-dev musl-dev wayland-protocols gcc
          meson build && ninja -C build && meson test -C build
          ' | docker run -i -v "$PWD":/wob -w /wob alpine:3.12
    - name: Test Archlinux
      stage: test
      services:
        - docker
      script:
        - |
          printf 'set -eu
          pacman -Syuu --noconfirm gcc pkgconf meson wayland wayland-protocols
          meson build && ninja -C build && meson test -C build
          ' | docker run -i -v "$PWD":/wob -w /wob archlinux:latest
    - name: Test FreeBSD
      stage: test
      os: freebsd
      language: c
      compiler: clang
      script:
        - sudo pkg install -y meson pkgconf wayland wayland-protocols
        # Fix for https://reviews.freebsd.org/D25554
        - sed -i '' 's/_POSIX_C_SOURCE 199506L/_POSIX_C_SOURCE 200112L/' log.c
        - meson build && ninja -C build && meson test -C build
    - name: Coding style check
      stage: test
      services:
        - docker
      script:
        - |
          printf 'set -eu
          apk update && apk add clang
          clang-format *.c tests/*.c --output-replacements-xml | (! grep "</replacement>" 1>/dev/null)
          ' | docker run -i -v "$PWD":/wob -w /wob alpine:3.12
    - name: Clang static analyzer
      stage: test
      services:
        - docker
      script:
        - |
          printf 'set -eu
          apk update && apk add meson wayland-dev musl-dev wayland-protocols gcc clang-analyzer
          scan-build meson build && scan-build --status-bugs ninja -C build
          ' | docker run -i -v "$PWD":/wob -w /wob alpine:3.12
    - name: Valgrind
      stage: test
      services:
        - docker
      script:
        - |
          printf 'set -eu
          apk update && apk add meson wayland-dev musl-dev wayland-protocols gcc valgrind
          meson build && meson test -C build --wrap="valgrind --leak-check=full --error-exitcode=2"
          ' | docker run -i -v "$PWD":/wob -w /wob alpine:3.12
    - name: Release to Github
      stage: release
      script: skip
      before_deploy:
        - mkdir "wob-${TRAVIS_TAG}"
        - mv include protocols tests *.c *.scd meson* LICENSE README.md "wob-${TRAVIS_TAG}"
        - tar -czf "wob-${TRAVIS_TAG}.tar.gz" "wob-${TRAVIS_TAG}"
      deploy:
        name: wob ${TRAVIS_TAG}
        provider: releases
        api_key:
          secure: S3jmdEiuUFr6VOUBI3G6zIvdMR5kCYttf8beWiNO2mu2ilHYC5e6xhQukVCUnwtgb9ZpbvrZi2XZ5OxElTK+YM5QZ2R7yYjlshtk8XjYhbLXJFmpnHrdqI1oAuP2tvYlk0THjjktMetou1peL/eXZVVlxQuH3U4+uuAAKZOYAgPQQwh3mjANhy/JqoOvjGC0mYu9AKExViyHLzV2jeqJw74P+cmxS7yklhN6sNzdhb2DyWifyPPBvpDP8IxolT81QUUXrtQINnt0rnk0i0b8R0HkVk0brIT7BddOAVLg5neiRquV+9yEMgGHI+kz2+vaVg7eKmtG+Ud6JpAOnMiYzo64EPfKuNEuDPPwRdC6fnwpEGA+gcFK3o+WmlqVeGst3FC2dRqtAY+6a5XmCUFM2yjpZbaRxBJZrciiwwRFVBreWz++76Kc3aIFlm7g3VpNgS7n2VmTKBM8X7ARnGuqY+pzRNsl1I6xydgLHiy5qmqaQPDdwjIKrf8So8zF+4VLQSdzkHd8oWocxaPabIMpCvadhmkt13bBtHN4y2FGLiy2XEfb8D6RpFPn6avZZYjt1YC87FDOSCZxHeMGAIq5Y6I3sHqK7TudC9b2Jlg8Qw+FQYFeYmNmq/pdLThbo+YDKsm9F6DzvSlB9DyYkwZq2cYgjCAw6gdVAUZuXJ4Ki20=
        file: "wob-${TRAVIS_TAG}.tar.gz"
        skip_cleanup: 'true'
        prerelease: true
        on:
          all_branches: true
          condition: true
