os: linux 
arch: ppc64le 
dist: bionic
sudo: required

env:
  global:
    - APK_TOOLS_URI="https://github.com/alpinelinux/apk-tools/releases/download/v2.10.3/apk-tools-2.10.3-ppc64le-linux.tar.gz"
    - APK_TOOLS_SHA256=75311787324dd56106b36d57cc33bcdacb8d089dbcd270669dab8d7eb76175d8

install:
  - wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.12.1/alpine-chroot-install
  - echo '5571ad4d17d14bb09ad23a75060f05553786e564' alpine-chroot-install | sha1sum -c || travis_terminate
  - sudo sh ./alpine-chroot-install -k 'ARCH CI QEMU_EMULATOR TRAVIS_.*' -p $ALPINE_PACKAGES

jobs:
  include:
    - name: Coding style check
      language: minimal
      env:
        - ALPINE_PACKAGES=clang
      script:
        - /alpine/enter-chroot clang-format *.c tests/*.c --output-replacements-xml | (! grep '</replacement>' 1>/dev/null)
    - &test
      name: Test GCC
      language: minimal
      env:
        - ALPINE_PACKAGES="gcc wayland-protocols wayland-dev meson musl-dev"
      script:
        - /alpine/enter-chroot meson build
        - /alpine/enter-chroot ninja -C build
        - /alpine/enter-chroot meson test -C build
      after_failure:
        - cat build/meson-logs/meson-log.txt
    - <<: *test
      name: Test Clang
      before_script:
        - /alpine/enter-chroot ln -sf /usr/bin/lld /usr/bin/ld
      env:
        # replace gcc with compiler-rt once it is available for ppc64le
        - ALPINE_PACKAGES="clang wayland-protocols wayland-dev meson musl-dev lld gcc"